<?php
defined( 'ABSPATH' ) || exit;

/**
 * Returns allowed HTML tags and attributes for wp_kses.
 *
 * Covers all HTML used in the product gallery output including
 * SVG elements, Swiper markup, form elements, and data attributes.
 *
 * @since 1.0.0
 *
 * @return array Allowed HTML tags with their attributes.
 */
function bdrvw_allowed_html() {

    $global_attributes = array(
        'class'            => true,
        'id'               => true,
        'style'            => true,
        'title'            => true,
        'role'             => true,
        'tabindex'         => true,
        'aria-label'       => true,
        'aria-live'        => true,
        'aria-atomic'      => true,
        'aria-current'     => true,
        'aria-controls'    => true,
        'aria-disabled'    => true,
        'aria-hidden'      => true,
        'aria-expanded'    => true,
        'aria-selected'    => true,
        'aria-describedby' => true,
        'aria-labelledby'  => true,
        'aria-haspopup'    => true,
        'aria-pressed'     => true,
        'aria-checked'     => true,
        'aria-valuenow'    => true,
        'aria-valuemin'    => true,
        'aria-valuemax'    => true,
        'data-*'           => true,
    );

    $allowed_tags = array(

        // Structural
        'div'      => $global_attributes,
        'span'     => $global_attributes,
        'section'  => $global_attributes,
        'article'  => $global_attributes,
        'aside'    => $global_attributes,
        'header'   => $global_attributes,
        'footer'   => $global_attributes,
        'main'     => $global_attributes,
        'figure'   => $global_attributes,
        'figcaption' => $global_attributes,
        'nav'      => $global_attributes,
        'ul'       => $global_attributes,
        'ol'       => array_merge( $global_attributes, array(
            'start'    => true,
            'reversed' => true,
            'type'     => true,
        )),
        'li'       => array_merge( $global_attributes, array(
            'value' => true,
        )),

        // Headings
        'h1'       => $global_attributes,
        'h2'       => $global_attributes,
        'h3'       => $global_attributes,
        'h4'       => $global_attributes,
        'h5'       => $global_attributes,
        'h6'       => $global_attributes,

        // Text / Inline
        'p'        => $global_attributes,
        'a'        => array_merge( $global_attributes, array(
            'href'     => true,
            'target'   => true,
            'rel'      => true,
            'download' => true,
        )),
        'strong'   => $global_attributes,
        'b'        => $global_attributes,
        'em'       => $global_attributes,
        'i'        => $global_attributes,
        'u'        => $global_attributes,
        's'        => $global_attributes,
        'small'    => $global_attributes,
        'sub'      => $global_attributes,
        'sup'      => $global_attributes,
        'br'       => $global_attributes,
        'hr'       => $global_attributes,
        'abbr'     => $global_attributes,
        'cite'     => $global_attributes,
        'code'     => $global_attributes,
        'pre'      => $global_attributes,
        'mark'     => $global_attributes,
        'del'      => array_merge( $global_attributes, array(
            'datetime' => true,
        )),
        'ins'      => array_merge( $global_attributes, array(
            'datetime' => true,
        )),
        'bdi'      => $global_attributes,
        'bdo'      => array_merge( $global_attributes, array(
            'dir' => true,
        )),
        'time'     => array_merge( $global_attributes, array(
            'datetime' => true,
        )),

        // Images
        'img'      => array_merge( $global_attributes, array(
            'src'           => true,
            'srcset'        => true,
            'sizes'         => true,
            'alt'           => true,
            'width'         => true,
            'height'        => true,
            'loading'       => true,
            'decoding'      => true,
            'fetchpriority' => true,
            'referrerpolicy' => true,
            'crossorigin'   => true,
            'usemap'        => true,
            'ismap'         => true,
        )),
        'picture'  => $global_attributes,
        'source'   => array_merge( $global_attributes, array(
            'src'    => true,
            'srcset' => true,
            'sizes'  => true,
            'media'  => true,
            'type'   => true,
        )),

        // Video / Audio
        'video'    => array_merge( $global_attributes, array(
            'src'         => true,
            'poster'      => true,
            'width'       => true,
            'height'      => true,
            'autoplay'    => true,
            'controls'    => true,
            'loop'        => true,
            'muted'       => true,
            'playsinline' => true,
            'preload'     => true,
        )),
        'audio'    => array_merge( $global_attributes, array(
            'src'      => true,
            'autoplay' => true,
            'controls' => true,
            'loop'     => true,
            'muted'    => true,
            'preload'  => true,
        )),
        'iframe'   => array_merge( $global_attributes, array(
            'src'             => true,
            'width'           => true,
            'height'          => true,
            'frameborder'     => true,
            'allow'           => true,
            'allowfullscreen' => true,
            'loading'         => true,
            'sandbox'         => true,
            'name'            => true,
        )),

        // Form elements
        'form'     => array_merge( $global_attributes, array(
            'action'  => true,
            'method'  => true,
            'enctype' => true,
            'name'    => true,
            'target'  => true,
            'novalidate' => true,
            'autocomplete' => true,
        )),
        'input'    => array_merge( $global_attributes, array(
            'type'         => true,
            'name'         => true,
            'value'        => true,
            'placeholder'  => true,
            'min'          => true,
            'max'          => true,
            'step'         => true,
            'checked'      => true,
            'disabled'     => true,
            'readonly'     => true,
            'required'     => true,
            'autofocus'    => true,
            'autocomplete' => true,
            'inputmode'    => true,
            'pattern'      => true,
            'size'         => true,
            'maxlength'    => true,
            'minlength'    => true,
            'multiple'     => true,
            'accept'       => true,
            'list'         => true,
            'form'         => true,
        )),
        'button'   => array_merge( $global_attributes, array(
            'type'     => true,
            'name'     => true,
            'value'    => true,
            'disabled' => true,
            'form'     => true,
        )),
        'label'    => array_merge( $global_attributes, array(
            'for' => true,
        )),
        'select'   => array_merge( $global_attributes, array(
            'name'         => true,
            'multiple'     => true,
            'disabled'     => true,
            'required'     => true,
            'size'         => true,
            'autocomplete' => true,
            'form'         => true,
        )),
        'option'   => array_merge( $global_attributes, array(
            'value'    => true,
            'selected' => true,
            'disabled' => true,
            'label'    => true,
        )),
        'optgroup' => array_merge( $global_attributes, array(
            'label'    => true,
            'disabled' => true,
        )),
        'textarea' => array_merge( $global_attributes, array(
            'name'         => true,
            'rows'         => true,
            'cols'         => true,
            'placeholder'  => true,
            'disabled'     => true,
            'readonly'     => true,
            'required'     => true,
            'maxlength'    => true,
            'minlength'    => true,
            'wrap'         => true,
            'autocomplete' => true,
            'form'         => true,
        )),
        'fieldset' => array_merge( $global_attributes, array(
            'disabled' => true,
            'form'     => true,
            'name'     => true,
        )),
        'legend'   => $global_attributes,

        // Table
        'table'    => array_merge( $global_attributes, array(
            'border'      => true,
            'cellpadding' => true,
            'cellspacing' => true,
            'width'       => true,
        )),
        'thead'    => $global_attributes,
        'tbody'    => $global_attributes,
        'tfoot'    => $global_attributes,
        'tr'       => $global_attributes,
        'th'       => array_merge( $global_attributes, array(
            'colspan' => true,
            'rowspan' => true,
            'scope'   => true,
            'abbr'    => true,
            'headers' => true,
        )),
        'td'       => array_merge( $global_attributes, array(
            'colspan' => true,
            'rowspan' => true,
            'headers' => true,
        )),
        'caption'  => $global_attributes,
        'colgroup' => array_merge( $global_attributes, array(
            'span' => true,
        )),
        'col'      => array_merge( $global_attributes, array(
            'span' => true,
        )),

        // SVG
        'svg'      => array_merge( $global_attributes, array(
            'xmlns'            => true,
            'viewBox'          => true,
            'viewbox'          => true,
            'width'            => true,
            'height'           => true,
            'fill'             => true,
            'stroke'           => true,
            'stroke-width'     => true,
            'stroke-linecap'   => true,
            'stroke-linejoin'  => true,
            'enable-background' => true,
            'preserveAspectRatio' => true,
            'x'                => true,
            'y'                => true,
            'opacity'          => true,
            'transform'        => true,
            'clip-path'        => true,
            'clip-rule'        => true,
            'mask'             => true,
            'overflow'         => true,
            'version'          => true,
            'xml:space'        => true,
            'xmlns:xlink'      => true,
            'focusable'        => true,
        )),
        'path'     => array_merge( $global_attributes, array(
            'd'              => true,
            'fill'           => true,
            'fill-rule'      => true,
            'fill-opacity'   => true,
            'stroke'         => true,
            'stroke-width'   => true,
            'stroke-linecap' => true,
            'stroke-linejoin' => true,
            'stroke-dasharray' => true,
            'stroke-dashoffset' => true,
            'stroke-opacity' => true,
            'opacity'        => true,
            'transform'      => true,
            'clip-path'      => true,
            'clip-rule'      => true,
        )),
        'circle'   => array_merge( $global_attributes, array(
            'cx'             => true,
            'cy'             => true,
            'r'              => true,
            'fill'           => true,
            'fill-opacity'   => true,
            'stroke'         => true,
            'stroke-width'   => true,
            'opacity'        => true,
            'transform'      => true,
        )),
        'ellipse'  => array_merge( $global_attributes, array(
            'cx'             => true,
            'cy'             => true,
            'rx'             => true,
            'ry'             => true,
            'fill'           => true,
            'fill-opacity'   => true,
            'stroke'         => true,
            'stroke-width'   => true,
            'opacity'        => true,
            'transform'      => true,
        )),
        'rect'     => array_merge( $global_attributes, array(
            'x'              => true,
            'y'              => true,
            'width'          => true,
            'height'         => true,
            'rx'             => true,
            'ry'             => true,
            'fill'           => true,
            'fill-opacity'   => true,
            'stroke'         => true,
            'stroke-width'   => true,
            'opacity'        => true,
            'transform'      => true,
        )),
        'line'     => array_merge( $global_attributes, array(
            'x1'             => true,
            'y1'             => true,
            'x2'             => true,
            'y2'             => true,
            'stroke'         => true,
            'stroke-width'   => true,
            'stroke-linecap' => true,
            'opacity'        => true,
            'transform'      => true,
        )),
        'polyline' => array_merge( $global_attributes, array(
            'points'         => true,
            'fill'           => true,
            'stroke'         => true,
            'stroke-width'   => true,
            'stroke-linecap' => true,
            'stroke-linejoin' => true,
            'opacity'        => true,
            'transform'      => true,
        )),
        'polygon'  => array_merge( $global_attributes, array(
            'points'         => true,
            'fill'           => true,
            'fill-rule'      => true,
            'stroke'         => true,
            'stroke-width'   => true,
            'opacity'        => true,
            'transform'      => true,
        )),
        'g'        => array_merge( $global_attributes, array(
            'fill'           => true,
            'fill-rule'      => true,
            'stroke'         => true,
            'stroke-width'   => true,
            'opacity'        => true,
            'transform'      => true,
            'clip-path'      => true,
        )),
        'defs'     => $global_attributes,
        'symbol'   => array_merge( $global_attributes, array(
            'viewBox'  => true,
            'viewbox'  => true,
            'width'    => true,
            'height'   => true,
            'fill'     => true,
            'overflow' => true,
        )),
        'use'      => array_merge( $global_attributes, array(
            'href'       => true,
            'xlink:href' => true,
            'x'          => true,
            'y'          => true,
            'width'      => true,
            'height'     => true,
            'fill'       => true,
            'stroke'     => true,
        )),
        'clipPath'  => $global_attributes,
        'linearGradient' => array_merge( $global_attributes, array(
            'x1'                => true,
            'y1'                => true,
            'x2'                => true,
            'y2'                => true,
            'gradientUnits'     => true,
            'gradientTransform' => true,
        )),
        'radialGradient' => array_merge( $global_attributes, array(
            'cx'                => true,
            'cy'                => true,
            'r'                 => true,
            'fx'                => true,
            'fy'                => true,
            'gradientUnits'     => true,
            'gradientTransform' => true,
        )),
        'stop'     => array_merge( $global_attributes, array(
            'offset'     => true,
            'stop-color' => true,
            'stop-opacity' => true,
        )),
        'text'     => array_merge( $global_attributes, array(
            'x'           => true,
            'y'           => true,
            'dx'          => true,
            'dy'          => true,
            'text-anchor' => true,
            'font-size'   => true,
            'font-family' => true,
            'font-weight' => true,
            'fill'        => true,
            'opacity'     => true,
            'transform'   => true,
        )),
        'tspan'    => array_merge( $global_attributes, array(
            'x'           => true,
            'y'           => true,
            'dx'          => true,
            'dy'          => true,
            'fill'        => true,
            'font-size'   => true,
            'font-family' => true,
            'font-weight' => true,
        )),
        'mask'     => array_merge( $global_attributes, array(
            'x'      => true,
            'y'      => true,
            'width'  => true,
            'height' => true,
            'maskUnits' => true,
            'maskContentUnits' => true,
        )),
        'title'    => $global_attributes,
        'desc'     => $global_attributes,
    );

    return apply_filters( 'bdrvw_allowed_html', $allowed_tags );
}